"""`rmic` command-line interface.

Commands:
    rmic init <agent-name>       Scaffold a new agent project directory.
    rmic validate <contract.json>  Validate a contract without sealing it.
    rmic seal <contract.json>      Compute anchor_embedding + contract_hash.
    rmic verify <contract.json>    Check a sealed contract's hash is intact.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from core.exceptions import ContractIntegrityError, ContractNotSealedError, InvalidContractError
from core.validation import validate_contract_dict

_QUICKSTART_TEMPLATE = '''"""Quickstart for {agent_name} — generated by `rmic init`."""
from __future__ import annotations

from rmic_guard import EnforcementEngine, RMICContract, ToolRegistry
from core.planning import PlannedToolCall


def main() -> None:
    contract = RMICContract.create(
        agent_id="{agent_name}",
        role_name="{role_name}",
        sector="general",
        role_description="Describe what this agent is allowed to do.",
        semantic_anchors=[
            "I perform the tasks described in my role.",
            "I do not perform actions outside my allowed tools.",
        ],
        allowed_actions=["example_tool"],
        forbidden_actions=["dangerous_tool"],
        # Runs offline out of the box. Set to True (or drop this line -- True
        # is the default) once you want semantic identity-drift scoring too;
        # that downloads a small local embedding model on first use.
        require_embedding=False,
    )

    tools = ToolRegistry()
    tools.register("example_tool", lambda **kwargs: {{"ok": True, "kwargs": kwargs}})
    tools.register("dangerous_tool", lambda **kwargs: {{"deleted": True}})

    engine = EnforcementEngine(contract=contract, tools=tools)

    for tool_name in ("example_tool", "dangerous_tool"):
        plan = PlannedToolCall(tool_name=tool_name, arguments={{}}, raw_text=tool_name)
        outcome = engine.evaluate_and_maybe_execute(plan, recent_ids=[], enforcement_mode="hard_rules_only")
        print(f"{{tool_name}}: {{outcome.decision}}")


if __name__ == "__main__":
    main()
'''

_CONTRACT_TEMPLATE = {
    "agent_id": "{agent_name}",
    "role_name": "{role_name}",
    "sector": "general",
    "role_description": "Describe what this agent is allowed to do.",
    "semantic_anchors": [
        "I perform the tasks described in my role.",
        "I do not perform actions outside my allowed tools.",
    ],
    "allowed_actions": ["example_tool"],
    "forbidden_actions": ["dangerous_tool"],
    "data_scope": {"accessible": [], "prohibited": [], "pii_categories": []},
    "parameter_constraints": {},
    "ids_warn_threshold": 0.35,
    "ids_block_threshold": 0.60,
    "drift_velocity_threshold": 0.05,
    "recovery_policy": "re-anchor",
    "compliance_tags": [],
    "contract_version": "1.0.0",
}

_PYPROJECT_TEMPLATE = '''[project]
name = "{agent_name}"
version = "0.1.0"
description = "RMIC-Guard agent: {agent_name}"
requires-python = ">=3.10,<3.14"
dependencies = ["rmic-guard[anthropic]"]
'''

_README_TEMPLATE = """# {agent_name}

Scaffolded by `rmic init`.

```bash
pip install -e .
python examples/quickstart.py
```

Edit `contracts/{agent_name}.json` to define the agent's semantic anchors,
allowed/forbidden tools, and data scope, then run:

```bash
rmic seal contracts/{agent_name}.json
```

to compute its anchor_embedding and contract_hash before use.
"""


def _cmd_init(args: argparse.Namespace) -> int:
    agent_name = args.agent_name
    root = Path(agent_name)
    if root.exists() and any(root.iterdir()):
        print(f"error: {root} already exists and is not empty", file=sys.stderr)
        return 1

    # agent_name may be given as a path ("rmic init teams/research-agent"),
    # in which case the *directory* is the full path but the generated
    # contract's agent_id/filename should be just the leaf component --
    # otherwise Path("contracts") / "/abs/path.json" silently discards the
    # "contracts/" prefix entirely (pathlib treats a leading "/" segment as
    # an absolute-path override, not a join).
    leaf_name = root.name or agent_name
    if not leaf_name or any(sep in leaf_name for sep in ("/", "\\")):
        print(f"error: {agent_name!r} does not contain a usable project name", file=sys.stderr)
        return 1

    (root / "contracts").mkdir(parents=True, exist_ok=True)
    (root / "examples").mkdir(parents=True, exist_ok=True)

    role_name = leaf_name.replace("_", " ").replace("-", " ").title()

    contract = dict(_CONTRACT_TEMPLATE)
    contract["agent_id"] = leaf_name
    contract["role_name"] = role_name
    (root / "contracts" / f"{leaf_name}.json").write_text(
        json.dumps(contract, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (root / "examples" / "quickstart.py").write_text(
        _QUICKSTART_TEMPLATE.format(agent_name=leaf_name, role_name=role_name), encoding="utf-8"
    )
    (root / "pyproject.toml").write_text(_PYPROJECT_TEMPLATE.format(agent_name=leaf_name), encoding="utf-8")
    (root / "README.md").write_text(_README_TEMPLATE.format(agent_name=leaf_name), encoding="utf-8")

    print(f"Created {root}/")
    print(f"  contracts/{leaf_name}.json")
    print("  examples/quickstart.py")
    print("  pyproject.toml")
    print("  README.md")
    print()
    print(f"Next: cd {root} && rmic seal contracts/{leaf_name}.json")
    return 0


def _cmd_validate(args: argparse.Namespace) -> int:
    path = Path(args.contract)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"error: {path} is not valid JSON: {exc}", file=sys.stderr)
        return 1
    try:
        validate_contract_dict(data, source=str(path))
    except InvalidContractError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f"{path}: valid")
    return 0


def _cmd_seal(args: argparse.Namespace) -> int:
    from core.contract_loader import seal_contract_file

    try:
        contract = seal_contract_file(args.contract, write_back=True)
    except InvalidContractError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f"{args.contract}: sealed")
    print(f"  contract_hash: {contract.contract_hash}")
    print(f"  anchor_embedding: {len(contract.anchor_embedding)}-dim vector")
    return 0


def _cmd_verify(args: argparse.Namespace) -> int:
    from core.contract_loader import load_contract

    try:
        load_contract(args.contract, verify_hash=True)
    except ContractNotSealedError as exc:
        print(f"{args.contract}: NOT SEALED — {exc}", file=sys.stderr)
        return 1
    except ContractIntegrityError as exc:
        print(f"{args.contract}: INTEGRITY FAILURE — {exc}", file=sys.stderr)
        return 1
    except InvalidContractError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f"{args.contract}: hash verified OK")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="rmic", description="RMIC-Guard command-line interface")
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="Scaffold a new agent project directory")
    p_init.add_argument("agent_name", help="Directory/agent id to create, e.g. research-agent")
    p_init.set_defaults(func=_cmd_init)

    p_validate = sub.add_parser("validate", help="Validate a contract JSON file")
    p_validate.add_argument("contract", help="Path to contract JSON file")
    p_validate.set_defaults(func=_cmd_validate)

    p_seal = sub.add_parser("seal", help="Compute anchor_embedding + contract_hash and write back")
    p_seal.add_argument("contract", help="Path to contract JSON file")
    p_seal.set_defaults(func=_cmd_seal)

    p_verify = sub.add_parser("verify", help="Verify a sealed contract's hash is intact")
    p_verify.add_argument("contract", help="Path to contract JSON file")
    p_verify.set_defaults(func=_cmd_verify)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
